import Head from 'next/head'
import Grid from '@material-ui/core/Grid'
import {makeStyles} from '@material-ui/core/styles'
import Hidden from '@material-ui/core/Hidden'
import withWidth from '@material-ui/core/withWidth'
import PropTypes from 'prop-types'
import LeftSideBar from '../components/SideBars/LeftSideBar'
import Shortcut from '../components/SideBars/Shortcut'
const useStyles = makeStyles((theme) => ({
  root: {
    flexGrow: 1,
  },

  left: {
    border: 'solid red',
    height: '100%',
    overflow: 'auto',
    maxHeight: '100vh',
  },
  center: {
    border: 'solid blue',
    overflow: 'auto',
    minHeight: '5vh',
    height: '85vh',
    padding: '0 40px',
  },
  right: {
    border: 'solid purple',
    overflow: 'auto',
    maxHeight: '85vh',
  },
}))

function Home(props) {
  const style = useStyles()
  const {width} = props
  return (
    <div className={style.root}>
      <Head>
        <title>Facebook</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='main'>
        <Grid container>
          <Hidden smDown>
            <Grid item xs={3} className={style.left}>
              <LeftSideBar />
              <Shortcut />
            </Grid>
          </Hidden>

          <Grid
            item
            xs={width === 'sm' ? 8 : 6 && width === 'xs' ? 12 : 6}
            className={style.center}
          >
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
            <p>center</p>
          </Grid>
          <Hidden xsDown>
            <Grid item xs={width === 'sm' ? 4 : 3} className={style.right}>
              right
            </Grid>
          </Hidden>
        </Grid>
        <Grid>
          <p>Current width: {width}</p>
        </Grid>
      </div>
    </div>
  )
}
Home.propTypes = {
  width: PropTypes.oneOf(['lg', 'md', 'sm', 'xl', 'xs']).isRequired,
}

export default withWidth()(Home)
