import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <p>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolores
        perferendis nesciunt voluptatibus error dolore? Quo laboriosam, quae
        repudiandae praesentium veritatis accusantium. Eligendi eaque cum fugit
        id obcaecati eum ab corrupti numquam at optio, tempora accusantium
        alias, modi laboriosam sapiente maxime, deleniti doloremque blanditiis
        hic sed pariatur itaque illo. Eaque, voluptatum, assumenda mollitia
        perferendis ab unde eum quasi ex in, hic sint illum quos! Modi
        voluptates quidem necessitatibus? Autem libero consectetur sequi magni.
        Eligendi fugiat laudantium reprehenderit numquam eum similique cumque
        totam voluptates illo! Quod reiciendis minus veritatis pariatur eaque
        voluptatum illum recusandae sunt ratione velit dignissimos explicabo,
        assumenda iusto deserunt id facilis quibusdam, eos cum laudantium. Iure
        ipsa adipisci aspernatur earum itaque explicabo possimus optio
        cupiditate incidunt, dignissimos impedit ad doloremque. Beatae eos autem
        ullam aut officia fuga dignissimos, consectetur, corporis tenetur earum,
        natus inventore? Assumenda libero doloribus non ipsam! Eius, cupiditate
        culpa consequatur animi dolorem non nulla maiores numquam mollitia
        suscipit quo tempora voluptatum itaque, autem aliquid cum quia, soluta
        minima obcaecati harum sapiente! Vel fuga, ipsa consectetur esse at
        asperiores eos soluta maiores dolorem quidem, repellendus error rem
        reprehenderit distinctio ex quibusdam natus nobis autem molestias
        voluptas illum est voluptatem magnam. Repudiandae consequatur
        perferendis exercitationem aliquam commodi fuga quisquam explicabo
        dolor, iure ipsum quas provident, temporibus esse veritatis harum
        expedita doloribus a, reiciendis sapiente saepe. Impedit mollitia,
        molestiae, pariatur deleniti dicta reiciendis nobis est laudantium
        molestias dolores debitis tempora rem sed, repellendus officia nostrum
        error vitae maiores animi odio eveniet odit? Voluptatum reiciendis
        consectetur pariatur maxime suscipit ipsum fugiat sequi impedit
        voluptatibus consequuntur harum, ducimus vero explicabo doloribus
        quaerat, hic rerum quod accusantium quo aut ipsam debitis aliquam
        facilis ipsa. Neque aspernatur amet temporibus soluta fuga alias. Totam,
        aspernatur eos. Consectetur explicabo odit molestias suscipit dolores
        autem ut, maxime ipsum, perferendis aperiam labore a amet omnis, debitis
        eligendi eum? Culpa possimus, atque perspiciatis pariatur nemo deleniti
        repellat corrupti voluptatem, voluptas ipsa eius fugiat, suscipit rerum?
        Natus deserunt cupiditate dolorem, officia ullam, quos voluptatum sed
        tempora architecto fugiat veniam illum nostrum odit numquam a beatae
        corrupti at consequuntur? Assumenda, ipsam dolore illum praesentium
        doloremque, cumque fuga, ipsum natus eum alias enim architecto maxime
        quia dignissimos vel consequuntur corporis rem libero necessitatibus
        nobis ullam perferendis perspiciatis incidunt. Eum perspiciatis
        blanditiis harum quod totam repudiandae pariatur a voluptatibus earum
        accusantium laboriosam numquam reiciendis vel, ut omnis amet quo.
        Tempora assumenda harum maxime recusandae laboriosam autem rem itaque
        corrupti vel fuga alias consequuntur sequi dicta veniam optio inventore
        expedita voluptates voluptatum cupiditate corporis, officiis, aspernatur
        dolore porro iure. Soluta praesentium repellat rerum voluptas,
        aspernatur excepturi fugit dolorem mollitia. Pariatur, asperiores
        tempora! Magnam quasi placeat, atque facilis in quaerat, beatae
        accusantium repellat aliquid corrupti a, reprehenderit officiis!
        Sapiente expedita beatae rerum quasi laborum fugiat totam tempore
        nesciunt ex blanditiis laboriosam, aspernatur ipsam consequatur ratione
        nemo alias saepe molestias assumenda fugit? Magnam eum, placeat
        assumenda enim minus ad, porro asperiores dolorum omnis similique
        dolores quas perferendis, laborum voluptatum! Illum magni, magnam nam
        consequuntur atque ullam. Omnis nihil atque, ratione cupiditate id quia
        porro cum.
      </p>
    </div>
  )
}
