import Head from 'next/head'
import NavBar from '../components/NavBar/NavBar'
import Testbar from '../components/NavBar/Testbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <NavBar /> */}
      <Testbar />
    </div>
  )
}
